COMP:Debian packaging

diff --git a/bin/foamSourceFiles b/bin/foamSourceFiles
--- a/bin/foamSourceFiles
+++ b/bin/foamSourceFiles
@@ -23,67 +23,56 @@
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Script
-#     foamPackBin <arch> [outputDir]
+#     foamSourceFiles <directory>
 #
 # Description
-#     Packs and compresses binary version of OpenFOAM for release
+#     Returns all the .C and .H files and Make/options
+#     and Make/files in a given directory.
 #
 #------------------------------------------------------------------------------
 
-if [ $# -eq 0 ]
+if [ $# -ne 1 ]
 then
-    echo "Error: architecture type expected, exiting"
-    echo
-    echo "Usage : ${0##*/} <arch> [outputDir]"
-    echo
-    exit 1
-fi
-arch=$1
-
-# base arch (w/o precision, optimization, etc)
-baseArch=$(echo "$arch" | sed -e 's@[DS]P.*$@@')
-
-timeStamp=$(date +%Y-%m-%d)
-packDir=$WM_PROJECT-$WM_PROJECT_VERSION
-packFile=${packDir}.${arch}_${timeStamp}.gtgz
-
-# add optional output directory
-if [ -d "$2" ]
-then
-    packFile="$2/$packFile"
-fi
-
-if [ -f $packFile ]
-then
-    echo "Error: $packFile already exists"
+    echo "Usage : ${0##*/} directory"
+    echo ""
+    echo "Returns all .C and .H files and Make/options and Make/files."
+    echo ""
     exit 1
 fi
 
-# check for essential directories
-for dir in $packDir $packDir/lib/$arch $packDir/applications/bin/$arch
-do
-    if [ ! -d $dir ]
-    then
-        echo "Error: directory $dir does not exist"
-        exit 1
-    fi
-done
+# canonical form (no double and no trailing dashes)
+packDir=$(echo "$1" | sed -e 's@//*@/@g' -e 's@/$@@')
 
-# get list of directories
-dirList=`foamBinDirs $packDir $arch`
-
-echo
-echo "Packing $arch ($baseArch) port of $packDir into $packFile"
-echo
-
-tar czpf $packFile $dirList
-
-if [ $? -eq 0 ]
+if [ ! -d $packDir ]
 then
-    echo "Finished packing and compressing file $packFile"
-else
-    echo "Error: failure packing $packFile"
-    rm -f $packFile 2>/dev/null
+    echo "Error: directory $packDir does not exist"
+    exit 1
 fi
+
+find -H $packDir               \
+    ! -type d                  \
+   \( -type f -o -type l \)    \
+    ! -name "*~"               \
+ -a ! -name ".*~"              \
+ -a ! -name "*.orig"           \
+ -a ! -name "*.dep"            \
+ -a ! -name "*.o"              \
+ -a ! -name "*.so"             \
+ -a ! -name "*.a"              \
+ -a ! -name "*.tgz"            \
+ -a ! -name "core"             \
+ -a ! -name "core.[1-9]*"      \
+ -a ! -name "libccmio*"        \
+| sed                          \
+ -e "\@$packDir/lib/@d"        \
+ -e '\@/\.git/@d'              \
+ -e '\@/\.tags/@d'             \
+ -e '\@applications/bin/@d'    \
+ -e '\@wmake/bin/@d'           \
+ -e '\@/t/@d'                  \
+ -e '\@/Make[.A-Za-z]*/[^/]*/@d'\
+ -e '\@/platforms/@d'          \
+ -e '\@libccmio.*/@d'          \
+ -e '\@/debian/@d'
 
 #------------------------------------------------------------------------------
